name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Install packages
      run: cd DotnetTemplate.Web && npm install