name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test

    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install packages
      run: cd DotnetTemplate.Web && npm install

    - name: Build app
      run: cd DotnetTemplate.Web && npm run build

    - name: Run linter
      run: cd DotnetTemplate.Web && npm run lint

    - name: Run typescript tests
      run: cd DotnetTemplate.Web && npm run test-with-coverage

  docker:
    name: Build docker image
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t anamic/dotnettemplate:${{ github.ref_name }} . 

      - name: Docker push
        run: docker push anamic/dotnettemplate:${{ github.ref_name }}

  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    # needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'anamic-dotnettemplate'
          heroku_email: 'ana.micu@softwire.com'
          dontuseforce: false